site_name: Starion Docs
theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
# nav:
#   - Getting Started:
#     - getting-started/index.md
#   - Formula:
#     - formula/index.md
#   - Distribute:
#     - distribute/index.md
#   - Integrations:
#     - integrations/index.md
#   - API:
#     - api/index.md
#   - Courses:
#     - courses/index.md
extra_css:
  - stylesheets/extra.css